// Die Reise: 5 Kapitel mit je 6 Levels.
// Zeichen siehe puzzle.js. "par" ist die kleinste Zahl an Teilen (vom Löser berechnet, tools/check-levels.mjs).

export const CHAPTERS = [
  { id: 'teich', name: 'Am Teich', intro: 'Leg Steine ins Wasser, damit die Tiere nach Hause kommen.', need: 0 },
  { id: 'schilf', name: 'Im Schilf', intro: 'Planken überbrücken zwei Felder auf einmal.', need: 8 },
  { id: 'bucht', name: 'Die Bucht', intro: 'Bei Ebbe tauchen Sandbänke auf. Schwimmstege gehen nur bei Flut.', need: 18 },
  { id: 'fluss', name: 'Der Fluss', intro: 'Flöße treiben hin und her. Die Tiere warten geduldig und fahren mit.', need: 28 },
  { id: 'heimweg', name: 'Heimweg', intro: 'Alles zusammen: Steine, Planken, Gezeiten und Flöße.', need: 38 },
];

export const LEVELS = [
  // ---------------------------------------------------------------- Am Teich
  {
    id: '1-1', chapter: 'teich', name: 'Der erste Stein',
    hint: 'Tippe aufs Wasser zwischen den Inseln. Dann hat Erna einen Weg.',
    map: [
      '.....',
      '.#A#.',
      '.....',
      '.#a#.',
      '.....',
    ],
    animals: { a: 'ente' }, stones: 3, par: 1,
  },
  {
    id: '1-2', chapter: 'teich', name: 'Trittsteine',
    hint: 'Kleine Inseln sparen Steine. Wenige Teile geben mehr Sterne.',
    map: [
      '.A...',
      '.#...',
      '.....',
      '..##.',
      '.....',
      '...#.',
      '...a.',
    ],
    animals: { a: 'ente' }, stones: 5, par: 3,
  },
  {
    id: '1-3', chapter: 'teich', name: 'Um den Felsen',
    map: [
      '.A...',
      '.#...',
      'RRR..',
      '.....',
      '...#.',
      '...a.',
    ],
    animals: { a: 'ente' }, stones: 6, par: 4,
  },
  {
    id: '1-4', chapter: 'teich', name: 'Inselhüpfen',
    map: [
      'A#.....',
      '##.....',
      '....#..',
      '.......',
      '.#...R.',
      '.....##',
      '.T....#',
      '......a',
    ],
    animals: { a: 'frosch' }, stones: 8, par: 6,
  },
  {
    id: '1-5', chapter: 'teich', name: 'Zu zweit',
    hint: 'Zwei Tiere dürfen sich einen Weg teilen. Das spart Steine.',
    map: [
      '.A.B.',
      '.#.#.',
      '.....',
      '.....',
      '..#..',
      '.ab#.',
    ],
    animals: { a: 'ente', b: 'frosch' }, stones: 5, par: 3,
  },
  {
    id: '1-6', chapter: 'teich', name: 'Der kleine See',
    map: [
      'B...A.',
      '#..R#.',
      '......',
      '.#..#.',
      '......',
      '.#....',
      'ab#...',
    ],
    animals: { a: 'frosch', b: 'igel' }, stones: 8, par: 6,
  },

  // ---------------------------------------------------------------- Im Schilf
  {
    id: '2-1', chapter: 'schilf', name: 'Die erste Planke',
    hint: 'Eine Planke liegt über zwei Feldern. Tippe das Planken-Symbol nochmal an, um sie zu drehen.',
    map: [
      '..A..',
      '..#..',
      '.....',
      '.....',
      '..#..',
      '..a..',
    ],
    animals: { a: 'igel' }, stones: 1, planks: 1, par: 1,
  },
  {
    id: '2-2', chapter: 'schilf', name: 'Stein und Planke',
    map: [
      '..A..',
      '..#..',
      '.....',
      '.....',
      '.....',
      '..#..',
      '..a..',
    ],
    animals: { a: 'igel' }, stones: 3, planks: 1, par: 2,
  },
  {
    id: '2-3', chapter: 'schilf', name: 'Quer gedacht',
    map: [
      'A......',
      '#......',
      '...##..',
      '.......',
      '..#....',
      '.......',
      '.....#a',
    ],
    animals: { a: 'hase' }, stones: 4, planks: 2, par: 5,
  },
  {
    id: '2-4', chapter: 'schilf', name: 'Schilfgürtel',
    map: [
      '...A...',
      '..T#T..',
      '.......',
      '.TT.TT.',
      '.......',
      '.......',
      '...#...',
      '...a...',
    ],
    animals: { a: 'hase' }, stones: 2, planks: 2, par: 2,
  },
  {
    id: '2-5', chapter: 'schilf', name: 'Zwei Wege',
    map: [
      'B...A',
      '#...#',
      '.....',
      '..#..',
      '.....',
      '#...#',
      'a...b',
    ],
    animals: { a: 'igel', b: 'hase' }, stones: 3, planks: 4, par: 5,
  },
  {
    id: '2-6', chapter: 'schilf', name: 'Im Dickicht',
    map: [
      'T.A...T',
      'T.#..BT',
      '.......',
      '.T..T..',
      '.T#.T..',
      '.......',
      '..T....',
      'a#T..b.',
      'T.....T',
    ],
    animals: { a: 'hase', b: 'igel' }, stones: 4, planks: 4, par: 6,
  },

  // ---------------------------------------------------------------- Die Bucht
  {
    id: '3-1', chapter: 'bucht', name: 'Ebbe',
    hint: 'Tippe auf den Mond, um Ebbe zu machen. Dann taucht die Sandbank auf.',
    map: [
      '..A..',
      '..#..',
      '..~..',
      '..~..',
      '..#..',
      '..a..',
    ],
    animals: { a: 'schildkroete' }, stones: 2, par: 0,
  },
  {
    id: '3-2', chapter: 'bucht', name: 'Der Schwimmsteg',
    hint: 'Schwimmstege liegen nur bei Flut auf Höhe der Wiese.',
    map: [
      '..A..',
      '..#..',
      '..=..',
      '..=..',
      '.....',
      '..#..',
      '..a..',
    ],
    animals: { a: 'schildkroete' }, stones: 4, par: 1,
  },
  {
    id: '3-3', chapter: 'bucht', name: 'Gezeiten wählen',
    map: [
      '...A...',
      '...#...',
      '.~~....',
      '.~.....',
      '.~...==',
      '.....=.',
      '.#.....',
      '.#a....',
    ],
    animals: { a: 'schildkroete' }, stones: 4, par: 2,
  },
  {
    id: '3-4', chapter: 'bucht', name: 'Watt',
    map: [
      'A#.....',
      '~~.....',
      '.~...R.',
      '.~.~...',
      '...~...',
      '...~~..',
      '....#..',
      '....#a.',
    ],
    animals: { a: 'fuchs' }, stones: 6, par: 1,
  },
  {
    id: '3-5', chapter: 'bucht', name: 'Hafen',
    map: [
      'B...A',
      '#==.#',
      '..=..',
      '..~~.',
      '...~.',
      '#....',
      'a...b',
    ],
    animals: { a: 'fuchs', b: 'schildkroete' }, stones: 3, planks: 4, par: 4,
  },
  {
    id: '3-6', chapter: 'bucht', name: 'Muschelbank',
    map: [
      '.A..B..',
      '.#..#..',
      '.~.....',
      '.~~..=.',
      '..~..=.',
      '.....=.',
      'R......',
      '.#..#..',
      '.a..b..',
    ],
    animals: { a: 'schaf', b: 'fuchs' }, stones: 3, planks: 3, par: 3,
  },

  // ---------------------------------------------------------------- Der Fluss
  {
    id: '4-1', chapter: 'fluss', name: 'Das Floß',
    hint: 'Das Floß treibt hin und her. Die Tiere warten am Ufer und fahren mit.',
    map: [
      '..A..',
      '..#..',
      '.....',
      ':::::',
      '.....',
      '..#..',
      '..a..',
    ],
    animals: { a: 'biber' }, rafts: [{ from: [0, 3], to: [4, 3] }], stones: 4, par: 2,
  },
  {
    id: '4-2', chapter: 'fluss', name: 'Mitfahren',
    map: [
      'A#.....',
      '.......',
      ':::::::',
      '.......',
      '.....#.',
      '.....#a',
    ],
    animals: { a: 'biber' }, rafts: [{ from: [0, 2], to: [6, 2], offset: 2 }], stones: 5, par: 2,
  },
  {
    id: '4-3', chapter: 'fluss', name: 'Zwei Strömungen',
    map: [
      '...A...',
      '...#...',
      ':::::::',
      '.......',
      '.#.....',
      ':::::::',
      '.......',
      '.....#.',
      '.....a.',
    ],
    animals: { a: 'otter' }, rafts: [{ from: [0, 2], to: [6, 2] }, { from: [6, 5], to: [0, 5] }], stones: 4, par: 2,
  },
  {
    id: '4-4', chapter: 'fluss', name: 'Stromabwärts',
    map: [
      'A#..:..',
      '....:..',
      '....:..',
      '....:..',
      '....:..',
      '....:..',
      '....:#a',
    ],
    animals: { a: 'otter' }, rafts: [{ from: [4, 6], to: [4, 0], offset: 1 }], stones: 3, planks: 1, par: 1,
  },
  {
    id: '4-5', chapter: 'fluss', name: 'Fähre',
    map: [
      'B.....A',
      '#.....#',
      '.......',
      ':::::::',
      '.......',
      '...#...',
      '.......',
      '#.....#',
      'a.....b',
    ],
    animals: { a: 'biber', b: 'otter' }, rafts: [{ from: [0, 3], to: [6, 3], offset: 3 }], stones: 4, planks: 4, par: 6,
  },
  {
    id: '4-6', chapter: 'fluss', name: 'Flussdelta',
    map: [
      '.A..:..',
      '.#..:..',
      '....:..',
      ':::::..',
      '.......',
      '..#....',
      '..:::::',
      '.......',
      '.....a#',
    ],
    animals: { a: 'otter' }, rafts: [{ from: [4, 0], to: [4, 3] }, { from: [0, 3], to: [3, 3], offset: 1 }, { from: [2, 6], to: [6, 6] }], stones: 3, planks: 3, par: 3,
  },

  // ---------------------------------------------------------------- Heimweg
  {
    id: '5-1', chapter: 'heimweg', name: 'Alte Bekannte',
    map: [
      'B..A...',
      '#..#...',
      '.......',
      '.~~~...',
      '....#..',
      '.......',
      '..#...#',
      '.....#b',
      'a#.....',
    ],
    animals: { a: 'ente', b: 'frosch' }, stones: 3, planks: 4, par: 5,
  },
  {
    id: '5-2', chapter: 'heimweg', name: 'Fährhafen',
    map: [
      '.A.....',
      '.#==...',
      '.......',
      ':::::::',
      '.......',
      '...~~~.',
      '.....#.',
      '.....a.',
    ],
    animals: { a: 'eule' }, rafts: [{ from: [0, 3], to: [6, 3], offset: 4 }], stones: 3, planks: 2, par: 2,
  },
  {
    id: '5-3', chapter: 'heimweg', name: 'Drei Freunde',
    map: [
      'A.B.C',
      '#.#.#',
      '.....',
      '..#..',
      '.....',
      '#.#.#',
      'c.a.b',
    ],
    animals: { a: 'schaf', b: 'eule', c: 'maus' }, stones: 3, planks: 4, par: 5,
  },
  {
    id: '5-4', chapter: 'heimweg', name: 'Schleuse',
    map: [
      'A#.....',
      '.......',
      '~~~.:..',
      '..~.:..',
      '..~.:..',
      '....:==',
      '....:.#',
      '....:.a',
    ],
    animals: { a: 'schwein' }, rafts: [{ from: [4, 7], to: [4, 2], offset: 2 }], stones: 3, planks: 2, par: 2,
  },
  {
    id: '5-5', chapter: 'heimweg', name: 'Abendrot',
    map: [
      '.B...A.',
      '.#...#.',
      '.......',
      ':::::::',
      '.......',
      '.~~.==.',
      '.......',
      '.#...#.',
      '.a...b.',
    ],
    animals: { a: 'maus', b: 'schwein' }, rafts: [{ from: [0, 3], to: [6, 3], offset: 1 }], stones: 3, planks: 4, par: 5,
  },
  {
    id: '5-6', chapter: 'heimweg', name: 'Endlich zu Hause',
    map: [
      'C..A..B',
      '#..#..#',
      '..:::::',
      '.......',
      '.~~.T..',
      '.......',
      ':::::..',
      '.......',
      '#..#..#',
      'b..c..a',
    ],
    animals: { a: 'ente', b: 'eule', c: 'schwein' }, rafts: [{ from: [2, 2], to: [6, 2] }, { from: [0, 6], to: [4, 6], offset: 2 }], stones: 4, planks: 4, par: 6,
  },
];
